apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: nginx-server
        image: nginx:1.23-alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: web-content
          mountPath: /usr/share/nginx/html
      - name: web-app-container
        image: frontend/react-app:v3.2.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 3000
          name: app
        env:
        - name: REACT_APP_API_URL
          value: "https://api.example.com"
        - name: NODE_ENV
          value: "production"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: web-content
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: frontend
spec:
  selector:
    app: web-app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP