#!/bin/bash

echo "================================================================================================"
echo "ANALYZING WHAT'S WORKING VS WHAT'S NOT"
echo "================================================================================================"
echo ""

echo "WHAT'S WORKING:"
echo "✅ 1. PR Creation via API"
echo "   - PR #8 was created by the GitHub App (clusterresourceupdatedev[bot])"
echo "   - This means recomm-pr-create CAN authenticate with GitHub"
echo "   - The GitHub App credentials (key.pem) ARE valid"
echo ""

echo "✅ 2. Installation exists in database"
echo "   - Installation ID 83795326 is in MongoDB"
echo "   - This was likely created during initial setup"
echo "   - NOT from a webhook (no installation webhook in logs)"
echo ""

echo "✅ 3. Manual webhooks to recomm-pr-create work"
echo "   - When we send webhooks manually, they process correctly"
echo "   - recomm-pr-create forwards them to pebble-agent-manager"
echo "   - Database gets updated properly"
echo ""

echo "❌ WHAT'S NOT WORKING:"
echo "1. GitHub → recomm-pr-create webhooks"
echo "   - When PR is closed/reopened on GitHub.com"
echo "   - GitHub is NOT sending webhooks to recomm-pr-create"
echo "   - No GitHub webhook requests in recomm-pr-create logs"
echo ""

echo "================================================================================================"
echo "THE KEY INSIGHT:"
echo "================================================================================================"
echo ""
echo "The GitHub App can CREATE PRs (outbound API calls work)"
echo "But GitHub doesn't NOTIFY about PR changes (inbound webhooks don't work)"
echo ""
echo "This suggests:"
echo "1. The GitHub App webhook URL is not configured, OR"
echo "2. Pull Request events are not subscribed, OR"
echo "3. The webhook URL is pointing somewhere else"
echo ""

echo "================================================================================================"
echo "TESTING THE THEORY:"
echo "================================================================================================"
echo ""

# Check if there's another service that might be receiving webhooks
echo "Checking for other webhook receivers in the cluster..."
kubectl get svc -A 2>/dev/null | grep -E "webhook|github|pr-ops" || echo "kubectl not available"

echo ""
echo "Checking if webhooks might be going to production instead of dev..."
echo "Production URL would be something like:"
echo "  https://api.gopebble.com/recomm-pr-create/public/webhook"
echo "  OR"
echo "  https://recomm-pr-create.gopebble.com/public/webhook"
echo ""

echo "================================================================================================"
echo "ACTION ITEMS TO FIX:"
echo "================================================================================================"
echo ""
echo "1. CHECK WEBHOOK URL:"
echo "   Go to: https://github.com/settings/apps/clusterresourceupdatedev"
echo "   → General section → Webhook URL field"
echo "   → Should be: http://a45747eda3b034438b4ba6fedd64516f-901326540.us-west-1.elb.amazonaws.com/public/webhook"
echo "   → If empty or different, UPDATE IT!"
echo ""
echo "2. CHECK EVENT SUBSCRIPTIONS:"
echo "   Same page → Permissions & events section"
echo "   → Subscribe to events → Make sure 'Pull request' is ✓ checked"
echo ""
echo "3. SAVE CHANGES:"
echo "   → Click 'Save changes' button at bottom"
echo ""
echo "4. TEST:"
echo "   → Go to PR #8 and add a comment"
echo "   → Check Recent Deliveries to see if webhook was sent"
echo ""

echo "================================================================================================"
echo "WHY OTHER THINGS WORK:"
echo "================================================================================================"
echo ""
echo "• PR Creation works because: It's an OUTBOUND API call from recomm-pr-create to GitHub"
echo "• Installation exists because: It was created during initial GitHub App installation"
echo "• Manual webhooks work because: We're bypassing GitHub and sending directly"
echo ""
echo "But GitHub → recomm-pr-create webhooks don't work because:"
echo "GitHub doesn't know WHERE to send the webhooks (missing/wrong webhook URL)"