#!/bin/bash

echo "================================================================================================"
echo "FINAL DIAGNOSIS - WEBHOOK URL CHECK"
echo "================================================================================================"
echo ""
echo "From your screenshots, I can confirm:"
echo "✅ Pull request events ARE subscribed"
echo "✅ Permissions are correctly set (Read and write)"
echo "✅ All PR-related events are checked"
echo ""
echo "The ONLY remaining issue must be the WEBHOOK URL!"
echo ""
echo "================================================================================================"
echo "CRITICAL: CHECK THE WEBHOOK URL FIELD"
echo "================================================================================================"
echo ""
echo "Go back to: https://github.com/settings/apps/clusterresourceupdatedev"
echo ""
echo "In the GENERAL section (at the top), look for:"
echo "  • Webhook URL field"
echo "  • Webhook secret field"
echo ""
echo "The Webhook URL MUST be:"
echo "  http://a45747eda3b034438b4ba6fedd64516f-901326540.us-west-1.elb.amazonaws.com/public/webhook"
echo ""
echo "If the Webhook URL field is:"
echo "  • EMPTY → That's the problem! Fill it in!"
echo "  • DIFFERENT → That's the problem! Update it!"
echo "  • CORRECT → Then let's test it now!"
echo ""
echo "================================================================================================"
echo "LET'S TEST RIGHT NOW"
echo "================================================================================================"
echo ""
echo "1. Make sure the Webhook URL is set correctly (as above)"
echo "2. Click 'Save changes' if you made any updates"
echo "3. Go to PR #8: https://github.com/azizdev1999/test-k8s-configs/pull/8"
echo "4. Close the PR (since we set it to 'open' in DB)"
echo "5. Check Recent Deliveries immediately"
echo "6. Check database status:"
echo ""

mongosh "mongodb://ecoagentuser:G9KnWA8tnisDPli@54.241.154.19:27017/ecoagent_dev" \
  --eval "db.pr_ops_pull_requests.findOne({pr_number: 8}, {pr_number: 1, pr_status: 1, status: 1, updated_at: 1, _id: 0})" \
  --quiet

echo ""
echo "If webhook URL was empty/wrong and you just fixed it:"
echo "  → The PR status should now update to 'closed' in MongoDB!"
echo "  → You'll see a new 'pull_request' webhook in Recent Deliveries!"