#!/bin/bash

echo "================================================================================================"
echo "FINDING PULL REQUEST WEBHOOKS IN RECENT DELIVERIES"
echo "================================================================================================"
echo ""

echo "Based on your screenshot, I can see:"
echo "✅ installation.created - 2025-09-01 15:12:37 (DELIVERED)"
echo "✅ installation.deleted - 2025-09-01 15:12:23 (DELIVERED)"
echo ""
echo "These are INSTALLATION webhooks, not PULL REQUEST webhooks!"
echo ""

echo "================================================================================================"
echo "TO FIND PULL REQUEST WEBHOOKS:"
echo "================================================================================================"
echo ""
echo "1. In the Recent Deliveries list, look for webhooks with these event types:"
echo "   • pull_request"
echo "   • pull_request_review"
echo "   • issue_comment (for PR comments)"
echo ""
echo "2. If you DON'T see any 'pull_request' webhooks, that confirms:"
echo "   → GitHub is NOT sending PR webhooks!"
echo "   → Even though installation webhooks ARE being sent"
echo ""

echo "================================================================================================"
echo "LET'S TRIGGER A TEST PR WEBHOOK NOW:"
echo "================================================================================================"
echo ""
echo "1. Open PR #8 in your browser:"
echo "   https://github.com/azizdev1999/test-k8s-configs/pull/8"
echo ""
echo "2. Do ONE of these actions:"
echo "   • Add a comment saying 'test webhook'"
echo "   • Click 'Reopen' if it's closed"
echo "   • Edit the PR title"
echo ""
echo "3. IMMEDIATELY go back to Recent Deliveries"
echo "   (Within 10 seconds - webhooks are sent instantly)"
echo ""
echo "4. Look for a NEW webhook entry:"
echo "   • If you see a new 'pull_request' webhook → Check if it's ✅ or ❌"
echo "   • If you DON'T see any new webhook → PR events are NOT subscribed!"
echo ""

echo "================================================================================================"
echo "CRITICAL CHECK: ARE PULL REQUEST EVENTS ENABLED?"
echo "================================================================================================"
echo ""
echo "Go to: https://github.com/settings/apps/clusterresourceupdatedev"
echo ""
echo "1. Scroll down to 'Permissions & events' section"
echo "2. Find 'Subscribe to events'"
echo "3. Make sure these are CHECKED ✓:"
echo "   □ Pull requests"
echo "   □ Pull request reviews"
echo "   □ Pull request review comments"
echo ""
echo "If 'Pull requests' is NOT checked:"
echo "   → That's the problem! GitHub isn't sending PR webhooks because you didn't subscribe!"
echo "   → Check the box and save!"
echo ""

echo "================================================================================================"
echo "WHY INSTALLATION WEBHOOKS WORK BUT PR WEBHOOKS DON'T:"
echo "================================================================================================"
echo ""
echo "• Installation webhooks are ALWAYS sent (can't be disabled)"
echo "• Pull request webhooks must be EXPLICITLY enabled in 'Subscribe to events'"
echo "• Each event type is a separate subscription"
echo ""
echo "This explains why:"
echo "✅ Installation events work (always enabled)"
echo "❌ Pull request events don't work (not subscribed)"