#!/bin/bash

echo "================================================================================================"
echo "TRIGGER REAL GITHUB WEBHOOK - PR #8"
echo "================================================================================================"
echo ""

PR_NUMBER=8
REPO="azizdev1999/test-k8s-configs"

echo "This script will help you trigger a real GitHub webhook for PR #8"
echo ""
echo "Current PR #8 status in database:"
mongosh "mongodb://ecoagentuser:G9KnWA8tnisDPli@54.241.154.19:27017/ecoagent_dev" \
  --eval "db.pr_ops_pull_requests.findOne({pr_number: $PR_NUMBER}, {pr_number: 1, pr_status: 1, status: 1, updated_at: 1, _id: 0})" \
  --quiet

echo ""
echo "================================================================================================"
echo "STEPS TO TRIGGER WEBHOOK AND GET EXACT ERROR:"
echo "================================================================================================"
echo ""
echo "1. OPEN PR #8 in browser:"
echo "   https://github.com/$REPO/pull/$PR_NUMBER"
echo ""
echo "2. PERFORM ONE OF THESE ACTIONS:"
echo "   Option A: Add a comment like 'Testing webhook'"
echo "   Option B: Close the PR (if open) or Reopen it (if closed)"
echo "   Option C: Edit the PR title or description"
echo ""
echo "3. IMMEDIATELY CHECK WEBHOOK DELIVERY:"
echo "   a) Go to: https://github.com/settings/apps/clusterresourceupdatedev"
echo "   b) Click 'Advanced' in left sidebar"
echo "   c) Scroll to 'Recent Deliveries' section"
echo "   d) Look for the most recent delivery (should be within seconds)"
echo ""
echo "4. GET THE EXACT ERROR:"
echo "   - If delivery shows ✅ (green) - webhook was sent successfully"
echo "   - If delivery shows ❌ (red) - click on it to see:"
echo "     • Headers tab: Shows request headers"
echo "     • Request tab: Shows the payload GitHub sent"
echo "     • Response tab: Shows THE EXACT ERROR MESSAGE"
echo ""
echo "5. COMMON ERRORS AND WHAT THEY MEAN:"
echo ""
echo "   'We couldn't deliver this payload: Service Timeout'"
echo "   → GitHub couldn't connect to the webhook URL within 10 seconds"
echo "   → The service might be down or URL is wrong"
echo ""
echo "   'We couldn't deliver this payload: failed to connect'"
echo "   → Network/firewall issue preventing GitHub from reaching the URL"
echo ""
echo "   'HTTP 404'"
echo "   → The webhook URL path doesn't exist"
echo "   → Check if URL ends with /public/webhook"
echo ""
echo "   'HTTP 401' or 'Invalid signature'"
echo "   → Webhook secret mismatch between GitHub and recomm-pr-create"
echo ""
echo "   'HTTP 500'"
echo "   → recomm-pr-create crashed while processing the webhook"
echo ""
echo "================================================================================================"
echo "ALTERNATIVE: CHECK IF WEBHOOK URL IS CONFIGURED"
echo "================================================================================================"
echo ""
echo "1. Go to: https://github.com/settings/apps/clusterresourceupdatedev"
echo "2. In 'General' section, look for 'Webhook URL' field"
echo "3. It should be:"
echo "   http://a45747eda3b034438b4ba6fedd64516f-901326540.us-west-1.elb.amazonaws.com/public/webhook"
echo ""
echo "4. If it's empty or different:"
echo "   → That's the problem! GitHub isn't sending webhooks because no URL is configured"
echo "   → Update it to the correct URL above"
echo "   → Click 'Save changes'"
echo ""
echo "5. Also check 'Webhook secret' field has a value"
echo "   (Don't change it unless you also update recomm-pr-create's .env)"