apiVersion: apps/v1
kind: Deployment
metadata:
  name: actuator-service
  namespace: pebble
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actuator
  template:
    metadata:
      labels:
        app: actuator
    spec:
      containers:
      - name: actuator
        image: pebble/actuator:v1.0.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"