apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbed-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testbed-app
  template:
    metadata:
      labels:
        app: testbed-app
    spec:
      containers:
      - name: testbed-cluster-1
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      - name: sidecar-container
        image: busybox:latest
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "200m"