apiVersion: apps/v1
kind: Deployment
metadata:
  name: konnectivity-agent
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: konnectivity-agent
  template:
    metadata:
      labels:
        app: konnectivity-agent
    spec:
      containers:
      - name: konnectivity-agent
        image: k8s.gcr.io/kas-network-proxy/proxy-agent:v0.0.33
        resources:
          requests:
            memory: "30Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "300m"