apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-dns
  template:
    metadata:
      labels:
        app: kube-dns
    spec:
      containers:
      - name: kubedns
        image: k8s.gcr.io/k8s-dns-kube-dns:1.22.20
        resources:
          requests:
            memory: "70Mi"
            cpu: "100m"
          limits:
            memory: "170Mi"
            cpu: "200m"
      - name: dnsmasq
        image: k8s.gcr.io/k8s-dns-dnsmasq-nanny:1.22.20
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "50Mi"
            cpu: "50m"
      - name: sidecar
        image: k8s.gcr.io/k8s-dns-sidecar:1.22.20
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
          limits:
            memory: "30Mi"
            cpu: "50m"