apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-operator
  template:
    metadata:
      labels:
        app: gpu-operator
    spec:
      containers:
      - name: gpu-operator
        image: nvidia/gpu-operator:v1.11.1
        resources:
          requests:
            memory: "48Mi"
            cpu: "3m"
          limits:
            memory: "60Mi"
            cpu: "4m"