apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-operator-validator
  namespace: gpu-operator
  labels:
    app: nvidia-operator-validator
spec:
  selector:
    matchLabels:
      app: nvidia-operator-validator
  template:
    metadata:
      labels:
        app: nvidia-operator-validator
    spec:
      containers:
      - name: nvidia-operator-validator
        image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v1.11.1
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # Resources will be added by PR-Ops
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
          readOnly: true
        - name: host-sys
          mountPath: /host/sys
          readOnly: true
        - name: host-dev
          mountPath: /host/dev
        securityContext:
          privileged: true
      volumes:
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-dev
        hostPath:
          path: /dev
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      serviceAccountName: nvidia-operator-validator